version: '3.8'

services:
  app:
    build: .
    container_name: hapi-fhir-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FHIR_BASE_URL=https://launch.smarthealthit.org/v/r4/fhir
    volumes:
      - ./public:/app/public:ro
    restart: unless-stopped
    networks:
      - hapi-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {r.statusCode === 200 ? process.exit(0) : process.exit(1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  hapi-network:
    driver: bridge